### ISSUE TITLE
action fail error

### ISSUE THREAD

**Issue by fr33dz** [jeansch/py-asterisk#8]
Hi,
I hope to  help me ,
I use py-asterisk to connect odoo and Asterisk.
and i get this error.

py-Asterisk action failed: Originate failed

thank you

**Comment by jeansch** [comment]
Do you have the complete traceback, and maybe the logs from your asterisk server ?

**Comment by fr33dz** [comment]
the log is here 
http://textup.fr/139122c0
thank you very much

**Comment by jeansch** [comment]
Hi, it looks like the problem comes from your asterisk. I cannot help you with that, py-asterisk is just relaying the failure. I suggest you to investigate the "Cant create SIP call - target device not registered".

[Sep 10 12:07:41] DEBUG[4683] manager.c: Running action 'Originate'
[Sep 10 12:07:41] DEBUG[4683] chan_sip.c: Asked to create a SIP channel with formats: (slin)
[Sep 10 12:07:41] DEBUG[4683] chan_sip.c: Allocating new SIP dialog for 643fd68d21bcd99c468149ba0abe26ac@87.106.7.155:1007 - INVITE (No RTP)
[Sep 10 12:07:41] DEBUG[4683] chan_sip.c: Cant create SIP call - target device not registered
